export {
  DURATION,
  EASING,
  TRANSITION_ENTER,
  TRANSITION_STAGGER_ITEM,
  TRANSITION_EXPAND,
  TRANSITION_INDICATOR,
  TRANSITION_HOVER_SCALE,
  STAGGER_INTERVAL,
  ENTRANCE_Y,
  REDUCED_MOTION_QUERY,
  getReducedTransition,
} from "../components/ui/_shared/motion";
