/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const website = {
  name: "yilangao.com",
  version: "1.3.7",
  release: {
    version: "1.3.7",
    name: "yilangao.com 1.3.7",
    releasedAt: "2026-04-23T16:14:36.144Z",
  },
} as const;
