/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const website = {
  name: "yilangao.com",
  version: "1.5.8",
  release: {
    version: "1.5.8",
    name: "yilangao.com 1.5.8",
    releasedAt: "2026-04-30T17:58:25.683Z",
  },
} as const;
