/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const website = {
  name: "yilangao.com",
  version: "1.3.11",
  release: {
    version: "1.3.11",
    name: "yilangao.com 1.3.11",
    releasedAt: "2026-04-24T18:16:51.960Z",
  },
} as const;
