import { defineConfig } from "tsup";
import { readFileSync, existsSync } from "node:fs";
import { join, basename, relative } from "node:path";
import type { Plugin } from "esbuild";

const BUILD_SCSS_DIR = join(import.meta.dirname, ".build-scss");

/**
 * esbuild plugin that replaces .module.scss imports with the JSON class map
 * generated by Phase 1 (compile-scss.mjs).
 */
function scssModulePlugin(): Plugin {
  return {
    name: "scss-module",
    setup(build) {
      build.onResolve({ filter: /\.module\.scss$/ }, (args) => {
        return {
          path: args.path,
          namespace: "scss-module",
          pluginData: { resolveDir: args.resolveDir },
        };
      });

      build.onLoad(
        { filter: /\.module\.scss$/, namespace: "scss-module" },
        (args) => {
          const uiRoot = join(
            import.meta.dirname,
            "..",
            "src",
            "components",
            "ui",
          );
          const resolveDir = args.pluginData.resolveDir as string;
          const scssBasename = basename(args.path, ".module.scss");
          const rel = relative(uiRoot, join(resolveDir, args.path));
          const jsonKey = rel
            .replace(/[/\\]/g, "__")
            .replace(".module.scss", "");
          const jsonPath = join(BUILD_SCSS_DIR, `${jsonKey}.json`);

          if (existsSync(jsonPath)) {
            const classMap = readFileSync(jsonPath, "utf-8");
            return {
              contents: `export default ${classMap};`,
              loader: "js",
            };
          }

          console.warn(
            `[scss-module] No compiled JSON for ${scssBasename}, using empty map`,
          );
          return {
            contents: `export default {};`,
            loader: "js",
          };
        },
      );
    },
  };
}

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  dts: true,
  external: ["react", "react-dom", "react/jsx-runtime", "framer-motion", "next", "next/link", "next/image", "next/dynamic", "next/navigation"],
  outDir: "dist",
  clean: true,
  esbuildPlugins: [scssModulePlugin()],
  async onSuccess() {
    const { readFileSync: rf, writeFileSync: wf, existsSync: ex } = await import("node:fs");
    const { join: j } = await import("node:path");
    const allCssPath = j(import.meta.dirname, ".build-scss", "all.css");
    if (ex(allCssPath)) {
      const css = rf(allCssPath, "utf-8");
      wf(j(import.meta.dirname, "dist", "styles.css"), css);
      console.log("Copied styles.css to dist/");
    }
  },
});
