/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const elan = {
  name: "Élan",
  version: "2.4.2",
  release: {
    version: "2.4.1",
    name: "Élan 2.4.1",
    releasedAt: "2026-04-03T22:20:53.802Z",
  },
} as const;
