/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const elan = {
  name: "Élan",
  version: "2.15.2",
  release: {
    version: "2.15.1",
    name: "Élan 2.15.1",
    releasedAt: "2026-04-28T19:39:09.904Z",
  },
} as const;
