/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const elan = {
  name: "Élan",
  version: "2.17.1",
  release: {
    version: "2.17.0",
    name: "Élan 2.17.0",
    releasedAt: "2026-06-21T05:55:29.331Z",
  },
} as const;
