#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const manifestPath = resolve(__dirname, '..', 'elan.json');
const playgroundElanPath = resolve(__dirname, '..', 'playground', 'src', 'lib', 'elan.ts');

const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
const prev = manifest.release.version;
const next = manifest.version;

manifest.release = {
  version: next,
  name: `Élan ${next}`,
  releasedAt: new Date().toISOString(),
};

writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
syncPlayground(manifest);
console.log(`Released: Élan ${prev} → ${next}`);
console.log(`  Name:     ${manifest.release.name}`);
console.log(`  Date:     ${manifest.release.releasedAt}`);

function syncPlayground(m) {
  const ts = `/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run \`npm run version:patch\` (or minor/major/release) from the repo root.
 */
export const elan = {
  name: ${JSON.stringify(m.name)},
  version: ${JSON.stringify(m.version)},
  release: {
    version: ${JSON.stringify(m.release.version)},
    name: ${JSON.stringify(m.release.name)},
    releasedAt: ${JSON.stringify(m.release.releasedAt)},
  },
} as const;
`;
  writeFileSync(playgroundElanPath, ts);
}
