#!/usr/bin/env node

/**
 * Multi-app version release script.
 *
 * Usage:
 *   node scripts/version-release.mjs [app]
 *
 * If [app] is omitted, defaults to "elan".
 *
 * Promotes the current dev version to a release: stamps release.version,
 * release.name, and release.releasedAt. Syncs the version file to all
 * registered sync targets.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const APPS = {
  elan: {
    displayName: 'Élan',
    manifest: 'elan.json',
    syncTargets: [
      { path: 'playground/src/lib/elan.ts', exportName: 'elan' },
    ],
  },
  'ascii-studio': {
    displayName: 'ASCII Art Studio',
    manifest: 'ascii-studio.json',
    syncTargets: [
      { path: 'ascii-tool/src/lib/version.ts', exportName: 'asciiStudio' },
    ],
  },
};

const appKey = process.argv[2] || 'elan';

const appConfig = APPS[appKey];
if (!appConfig) {
  console.error(`Unknown app: "${appKey}". Available: ${Object.keys(APPS).join(', ')}`);
  process.exit(1);
}

const manifestPath = resolve(root, appConfig.manifest);
const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
const prev = manifest.release.version;
const next = manifest.version;

manifest.release = {
  version: next,
  name: `${appConfig.displayName} ${next}`,
  releasedAt: new Date().toISOString(),
};

writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

for (const target of appConfig.syncTargets) {
  syncTarget(manifest, target);
}

console.log(`Released: ${appConfig.displayName} ${prev} → ${next}`);
console.log(`  Name:     ${manifest.release.name}`);
console.log(`  Date:     ${manifest.release.releasedAt}`);

function syncTarget(m, target) {
  const targetPath = resolve(root, target.path);
  const targetDir = dirname(targetPath);
  if (!existsSync(targetDir)) mkdirSync(targetDir, { recursive: true });

  const ts = `/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const ${target.exportName} = {
  name: ${JSON.stringify(m.name)},
  version: ${JSON.stringify(m.version)},
  release: {
    version: ${JSON.stringify(m.release.version)},
    name: ${JSON.stringify(m.release.name)},
    releasedAt: ${JSON.stringify(m.release.releasedAt)},
  },
} as const;
`;
  writeFileSync(targetPath, ts);
}
