#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const manifestPath = resolve(__dirname, '..', 'elan.json');
const playgroundElanPath = resolve(__dirname, '..', 'playground', 'src', 'lib', 'elan.ts');

const level = process.argv[2];
if (!['patch', 'minor', 'major'].includes(level)) {
  console.error('Usage: node scripts/version-bump.mjs <patch|minor|major>');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
const [major, minor, patch] = manifest.version.split('.').map(Number);

const next = {
  major: `${major + 1}.0.0`,
  minor: `${major}.${minor + 1}.0`,
  patch: `${major}.${minor}.${patch + 1}`,
}[level];

const prev = manifest.version;
manifest.version = next;

writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
syncPlayground(manifest);
console.log(`Élan ${prev} → ${next} (${level})`);

function syncPlayground(m) {
  const ts = `/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run \`npm run version:patch\` (or minor/major/release) from the repo root.
 */
export const elan = {
  name: ${JSON.stringify(m.name)},
  version: ${JSON.stringify(m.version)},
  release: {
    version: ${JSON.stringify(m.release.version)},
    name: ${JSON.stringify(m.release.name)},
    releasedAt: ${JSON.stringify(m.release.releasedAt)},
  },
} as const;
`;
  writeFileSync(playgroundElanPath, ts);
}
