#!/usr/bin/env node

/**
 * Multi-app version bump script.
 *
 * Usage:
 *   node scripts/version-bump.mjs <patch|minor|major> [app]
 *
 * If [app] is omitted, defaults to "elan".
 *
 * App configs are defined in the APPS map below. When adding a new app to the
 * monorepo, register it here with its manifest path, sync targets, and display
 * name. This is the single source of truth for how versioning works across apps.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const APPS = {
  elan: {
    displayName: 'Élan',
    manifest: 'elan.json',
    syncTargets: [
      { path: 'playground/src/lib/elan.ts', exportName: 'elan' },
    ],
  },
  'ascii-studio': {
    displayName: 'ASCII Art Studio',
    manifest: 'ascii-studio.json',
    syncTargets: [
      { path: 'ascii-tool/src/lib/version.ts', exportName: 'asciiStudio' },
    ],
  },
};

const level = process.argv[2];
const appKey = process.argv[3] || 'elan';

if (!['patch', 'minor', 'major'].includes(level)) {
  console.error('Usage: node scripts/version-bump.mjs <patch|minor|major> [app]');
  console.error(`Available apps: ${Object.keys(APPS).join(', ')}`);
  process.exit(1);
}

const appConfig = APPS[appKey];
if (!appConfig) {
  console.error(`Unknown app: "${appKey}". Available: ${Object.keys(APPS).join(', ')}`);
  process.exit(1);
}

const manifestPath = resolve(root, appConfig.manifest);
const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
const [major, minor, patch] = manifest.version.split('.').map(Number);

const next = {
  major: `${major + 1}.0.0`,
  minor: `${major}.${minor + 1}.0`,
  patch: `${major}.${minor}.${patch + 1}`,
}[level];

const prev = manifest.version;
manifest.version = next;

writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

for (const target of appConfig.syncTargets) {
  syncTarget(manifest, appConfig, target);
}

console.log(`${appConfig.displayName} ${prev} → ${next} (${level})`);

function syncTarget(m, config, target) {
  const targetPath = resolve(root, target.path);
  const targetDir = dirname(targetPath);
  if (!existsSync(targetDir)) mkdirSync(targetDir, { recursive: true });

  const ts = `/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const ${target.exportName} = {
  name: ${JSON.stringify(m.name)},
  version: ${JSON.stringify(m.version)},
  release: {
    version: ${JSON.stringify(m.release.version)},
    name: ${JSON.stringify(m.release.name)},
    releasedAt: ${JSON.stringify(m.release.releasedAt)},
  },
} as const;
`;
  writeFileSync(targetPath, ts);
}
