/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const asciiStudio = {
  name: "ASCII Art Studio",
  version: "0.6.2",
  release: {
    version: "0.6.1",
    name: "ASCII Art Studio 0.6.1",
    releasedAt: "2026-04-21T14:17:12.095Z",
  },
} as const;
