/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const asciiStudio = {
  name: "ASCII Art Studio",
  version: "0.6.28",
  release: {
    version: "0.6.27",
    name: "ASCII Art Studio 0.6.27",
    releasedAt: "2026-05-08T05:38:58.113Z",
  },
} as const;
