/**
 * Auto-generated by scripts/version-bump.mjs and scripts/version-release.mjs.
 * Do not edit manually — run the appropriate version command from the repo root.
 */
export const asciiStudio = {
  name: "ASCII Art Studio",
  version: "0.6.23",
  release: {
    version: "0.6.22",
    name: "ASCII Art Studio 0.6.22",
    releasedAt: "2026-04-28T22:08:26.119Z",
  },
} as const;
